---
title: "Casestudy8"
author: "Austin"
date: "10/27/2022"
output: 
  html_document:
    keep_md: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(knitr)
library(tidyverse)
library(downloader)
library(corrplot)
library(stringi)
library(lubridate)
library(riem)
library(ggplot2)
```

```{r}
dat <- tempfile()
download("https://github.com/WJC-Data-Science/DTS350/raw/master/sales.csv", "dat", mode = 'wb')
dat<- read_csv("dat")
head(dat)
str(dat)
```

```{r time changes}
dattimezone <- dat %>%
  with_tz(dat, tzone = "Us/Mountain")

datnew <- dattimezone %>%
mutate(hour = ceiling_date(Time, "hour"),
        day = ceiling_date(Time, "day"),
        week = ceiling_date(Time, "week"),
        month = ceiling_date(Time, "month"))
```

```{r day, weekly, monthly}
month <- datnew %>%
  mutate(month = month(month)) %>%
  group_by(Name, month) %>%
  summarize(across(Amount,sum))

monthly <- ggplot(aes(data=montht, month, Amount, fill = Name)) +
  geom_line() +
  facet_wrap(~Name) +
  labs(x = "Month",
       y = "Sales",
       title = "Sales of each company by month") +
  theme_bw()

week <- datnew%>%
  mutate(week = week(week)) %>%
  group_by(Name, week) %>%
  summarize(across(Amount,sum))

weekly <- ggplot(aes(data = week, week, Amount, fill = Name)) +
  geom_line() +
  facet_wrap(~Name, scales = 'free') +
  labs(x = "Week",
       y = "Sales",
       title = "Sales of each company by Week") +
  theme_bw()

day <- datnew %>%
  mutate(day = wday(day)) %>%
  group_by(Name, day) %>%
  summarize(across(Amount,sum))

 daily <-  ggplot(aes(data= day, day, Amount, color = Name)) +
  geom_line() +
  facet_wrap(~Name, scales = 'free') +
  labs(x = "Day",
       y = "Sales",
       title = "Sales of each company by Day") +
  theme_bw()
```


```{r Final visual}

sales <- datnew %>%
  mutate(Name = as.factor(fct_reorder(Name, Amount))) %>%
  arrange(desc(Amount))
  
  ggplot(aes(data = sales, Name, Amount, fill = Name)) +
    geom_col() +
    labs(x = 'Company name', y = 'Sales', title = 'Total Sales from each company')+
    theme_bw() 
```

