---
title: "Task18"
author: "Austin"
date: "11/8/2022"
output: 
  html_document:
    keep_md: TRUE
    code_folding: 'hide'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(knitr)
library(tidyverse)
library(downloader)
library(corrplot)
library(stringi)
library(stringr)
library(dplyr)
library(ggplot2)
library(haven)
library(readxl)
library(lubridate)
library(readr) 
library(haven)
library(riem)
library(tidyquant)
library(timetk)
library(DT) 
library(dygraphs)
library(maps)
library(USAboundaries)
library(USAboundariesData)
library(sf)
library(ggsflabel)
library(USAboundariesData)
library(ggsflabel)

```

```{r}
cities <- us_cities() 
head(cities)
states <- us_states()
counties <- us_counties()

```

```{r}
idaho <- us_counties(states = "ID")
usmap <- sf::st_as_sf(map("state", plot = FALSE, fill = TRUE))
head(usmap)
alaskahawaii <- cities %>%
  filter(state_name != 'Alaska', state_name != 'Hawaii')
```

```{r}
orderedcities <- alaskahawaii %>%
  group_by(state_name) %>%
  arrange(desc(population))
head(orderedcities)

Biggestcities <- orderedcities %>%
  slice(1:3)
first <- Biggestcities %>%
  slice(1:1)
second <- Biggestcities %>%
  slice(2:2)
third <- Biggestcities %>%
  slice(3:3)
head(third)
```

```{r}
USmap <- ggplot() +
  geom_sf(data = usmap, fill = NA) +
  geom_sf(data = idaho, fill = NA) +
  geom_sf(data = first, aes(size = population/1000), color = "lightblue") +
  geom_sf(data = second, aes(size = population/1000), color = "royalblue") +
  geom_sf(data = third, aes(size = population/1000), color = "darkblue") +
  geom_sf_label(data = first, aes(label = city), color = "black", nudge_x = 1.5, nudge_y = 1, size = 2) +
  scale_size_continuous(name = 'Population\n(1,000)') +
  labs(title="Largest cities is the United State", x="Latitude",y="Longitude") +
  theme_bw() 
USmap
```

