---
title: "Task 11"
author: "Austin"
date: "9/29/2022"
output: 
  html_document:
    keep_md: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(ggstance)
```

```{r}
dat <- read_csv("fandango.csv")
head(dat)
str(dat)
```

```{r}
table1 <- dat %>%
  select(FILM, Fandango_Ratingvalue, RT_norm_round, Metacritic_norm_round, IMDB_norm_round) %>%
  pivot_longer(2:5, names_to = "Rating_site", values_to = "Rating")
table1

only_20 <- head(table1, 20)

Graph1 <- ggplot(data = only_20, mapping = aes(x= FILM, y= Rating, fill = Rating_site, position_fill())) +
  geom_col() +
  coord_flip()+
  labs(title = "Movie Ratings By Website") +
  theme_bw()
Graph1

ggsave("Graph1.png")


```
My graphic shows the most similar rating scales between all four websites that we used. I stacked them to see if there is a trend on which rating site rates movies the highest on average. It is hard to determine this off of this grpahic alone but we can see most of the time fandango has the highest ratings out of all the rating sites.
