---
title: "Case Study 3"
author: "Austin"
date: "9/12/2022"
output: html_document
keep_md: TRUE
editor_options: 
  chunk_output_type: console
---

```{r loading packages}
library(readr)
library(tidyverse)
library(knitr)
library(downloader)
library(dplyr)
```


```{r gapminder}
install.packages("gapminder")
library(gapminder)
head(gapminder)
```

```{r Taking out Kuwait}
No_more_Kuwait <- filter(gapminder, country != "Kuwait")
No_more_Kuwait
```

```{r Graphic 1}
Graph1 <- ggplot(data = No_more_Kuwait) +
  geom_point(mapping = aes(size = pop/100000, x = lifeExp, y = gdpPercap, color = continent, group = year)) +
  facet_wrap(~ year, nrow = 1) +
  scale_y_continuous(trans = "sqrt") +
  scale_size_continuous(name = "Population (100k)") +
  xlab("Life Expectancy") +
  ylab("GDP per capita") +
  theme_bw()

Graph1
```

```{r Creating weighted Average}
Weighted_Average  <- No_more_Kuwait %>%
  group_by(continent, year) %>%
  summarise(average = weighted.mean(gdpPercap), population = pop/10000)
Weighted_Average
```


```{r Graphic 2}
Graph2 <- ggplot(data = No_more_Kuwait) +
  geom_point(data = Weighted_Average,aes(x = year, y = average, size = population)) +
  geom_line(data = Weighted_Average,aes(x = year, y = average)) +
  geom_point(aes(x = year, y = gdpPercap, color = continent)) +
  geom_line(aes(x = year, y = gdpPercap, color = continent, group = country)) +
  scale_size_continuous(name = "Population (100k)") +
  facet_wrap(~ continent, nrow = 1) +
  xlab("Year") +
  ylab("GDP per capita") 

Graph2
```



